### ISSUE TITLE
Hangul Font draw Routine Problem #2

### ISSUE THREAD

**Issue by Crisp2013** [009342/pokered#4]
![cap 2018-06-05 08-59-32-012](https://user-images.githubusercontent.com/24960466/40948329-d85d7a46-68a2-11e8-8af9-f1f692eca7f3.png)
![cap 2018-06-05 08-58-03-505](https://user-images.githubusercontent.com/24960466/40948330-da2aa2f4-68a2-11e8-8965-de20269ba10e.png)

첫번째로 메모리로 사용되는 vram 부분이 HUD를 침범합니다.
두번째로 똑같은 문장을 두번 호출하는 경우 폰트가 정상적으로 vram에 복제되지 않습니다.

**Comment by 009342** [comment]
수정했습니다.
